repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.5      
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
      # types_or: [ python, pyi ] # exclude jupyter notebooks      
    # Run the formatter.
    - id: ruff-format 
      types_or: [ python, pyi ] # exclude jupyter notebooks    

# - repo: https://github.com/biomejs/pre-commit
#   rev: v2.2.4
#   hooks:
#     - id: biome-check
#       additional_dependencies: ["@biomejs/biome@2.2.4"]
#       files: ^frontend/
#       # exclude: ^frontend/src/plugins/
#       args: ["--unsafe"]

- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
      files: \.ipynb$

# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v1.17.0
#   hooks:
#     - id: mypy
